fix: support objects with null prototype as `HeadersInit` (#81)
Currently, if an object is created with the null prototype, e.g.

```typescript
const headers = Object.create(null);
```

attempting to instantiate a `Headers` object with this polyfill throws
an error:

```
TypeError: Cannot read properties of undefined (reading 'name')
```

because `headers.constructor` is undefined.

@kettanaito

---------

Co-authored-by: Artem Zakharchenko <kettanaito@gmail.com>