fix: add disposable methods for TypeScript 5.2 compatibility (#82)
Hi 👋 

First off, thanks for you work on this 🙇 It's making my life a lot
easier 💜

I recently ran into a problem when updating `JSDOM` in my project, where
the return type wasn't compatible any more:

```
error TS2322: Type 'typeof Headers$1' is not assignable to type '{ new
  (init?: HeadersInit | undefined): Headers; prototype: Headers; }'.
    The types returned by 'prototype.entries()' are incompatible between these types.
      Property '[Symbol.dispose]' is missing in type 'IterableIterator<[string, string]>' but
  required in type 'HeadersIterator<[string, string]>'.

  6 globalThis.Headers = HeadersPolyfill;
    ~~~~~~~~~~~~~~~~~~

    node_modules/typescript/lib/lib.esnext.disposable.d.ts:36:5
      36     [Symbol.dispose](): void;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
      '[Symbol.dispose]' is declared here.
```


This PR fixes this and makes makes the polyfill compatible with
TypeScript 5.2+ 🎉

**Background**

TypeScript 5.2 added `[Symbol.dispose]` to iterator types as part of the
[Explicit Resource
Management](https://github.com/tc39/proposal-explicit-resource-management)
proposal.
This property was missing in the polyfills iterators, making them
incompatible with e.g. current JSDOM and TypeScript.

**Change**

This removes the explicit `IterableIterator` return type annotations
from the `entries()`, `keys()` and `values()` generator functions in
favor of the `Generator` type.

---------

Co-authored-by: Artem Zakharchenko <kettanaito@gmail.com>